### ISSUE TITLE
✨ Feat: Inline CSS

### ISSUE THREAD

**Issue by PaleBluDot** [PaleBluDot/e11ty#4]
### Is this request for a new request or updating an existing feature?

New

### What feature would you like?

Move styles that are on custom CSS files and inline them into the HTML. 

### **INPUT** 

```html
<p class="text">Inlining classes to HTML style attritubute.</p>
```

```css
.text {
  font-size:16px; 
  line-height: 1.3; 
  color: #f3ef07;
}
```

### **OUTPUT**

```html
<p style="font-size:16px; line-height: 1.3; color: #f3ef07;">Inlining classes to HTML style attritubute.</p>
```
